drop .yarnrc for now
Before it ever gets restored, need to resolve system test failure:

Error: Cannot find module '/rails/.yarn/releases/yarn-1.22.19.cjs'